[build.environment]
  YARN_FLAGS='--pure-lockfile'
  NODE_VERSION='16.7.0'

  DEFAULT_CHAIN_ID='42'
  INFURA_API_KEY='f1c9535b961648f7bd18209b00e11163'
  FORTMATIC_API_KEY='pk_test_11610B956E1411D8'
  ETHERSCAN_API_KEY='1N7T6P46WEQ6AENHAGCIGY3PS5NZD8KCDJ'
  IPFS_HOST_ADDRESS='https://ipfs.kleros.io'
  IPFS_GATEWAY_ADDRESS='https://ipfs.kleros.io'
  USER_SETTINGS_API_BASE_URL='https://iioeu1ljqf.execute-api.us-east-2.amazonaws.com/mainnet'
  LINGUO_CONTRACT_ADDRESSES='{"1":{"de|en":["0x54f1f7b58c1Dc646a6c639C5d909B62652129b33","0x950f5AB863075C685227EfEDb41Ef167Be0099ad"],"en|es":["0x460f688f655610de5e3d92beb7892fa200b9060d","0xD8F8019c025C2Ba6745543D9a3C338DE1b98C103"],"en|fr":["0xFEe86325d5C96AE9E20EaBe7B157813c67bBccFA","0xf1A9589880DbF393F32A5b2d5a0054Fa10385074"],"en|ja":["0x5Cd1ff55282db11e526Fe13fA0F7C014f74acF11","0xc3162705Af0e10108FF837E450A14669b2711129"],"en|ko":["0xf8D4c1436ACA89A5DEEf36F06f662bAdfEb5AE63","0xFE721DD8Ac8e47A4228A6147A25C65136f213EaA"],"en|pt":["0x48032Ad54DB49d8E0d4f135A687b98E5731961f9","0x1c839fd542563182BFD0C337c8AaD1Be412F0fd2"],"en|ru":["0x0Bc3B51673dCdF3b45c628066761dA7331E8fBA2","0x464c84c41f3C25Ba5a75B006D8B20600A8777306"],"en|tr":["0xa3E4348BDDc32AfcedC5e088e0E21FD6154A0180","0x44863f5b7AAb7ceE181C0d84E244540125eF7AF7"],"en|zh":["0xaB0D90943A58b1A64c0171Ee8e743d9998Be6AC3","0xD67C12734dC12240a6324Db63ccd426964B71Fe7"]},"42":{"de|en":["0x8A4290298D65717a3BaEd546e4Ef9Eb2fe0b187D","0x5Af02E0E04c2042345E15Ed6dc7CC0c220f2C2Fa"],"en|es":["0x082aA0BeBE8C32042F77d123B6a657Fe907D8C33","0x6eb2D062E808a67828d27aD3926912C9309E5417"],"en|fr":["0x963Df99387a2b350264B5847ff9AbFF674e7BdFA","0x152c7F0948Fd0B2741a934aA7bfceB41cd4b5bFD"],"en|ja":["0x8B819D13d90Fcf9F0a235fe85d860E3C9763D470","0x033B08AAC5A3a2E7C306dd5Ee360904eC8d45DF6"],"en|ko":["0xe026cA59Bc31960D3060390D8667ceBc5D42B46d","0x499aD7D07f6EF0bD17656559312D0DdCBA0e79Ce"],"en|pt":["0xaD9Dec9c66cEbAa7e8624a528f65A3FA1Df8027d","0xb9534aB9b71e26949F9bdF9C05897Ee4619d144F"],"en|ru":["0xF4E6294201Ef99f1E83586Ef5AC8bCBaA4DB45CF","0x243a0431DE8d0B6D9837B53d3A10088b53B52918"],"en|tr":["0x10Dde936662A674F35ab36641017342B75Bb1D58","0xB93b8c9FD90724C036Ac56c5D3306333A67cFbFB"],"en|zh":["0xffb2BB47F4CD36426134706A849590471622519C","0xBc19B6fBAEEC0a2b50f3AD6F53b670ac03Bd1C6F"]},"77":{"de|en":["0x5EC045788659159e2E2A725361DF4Dc271edB7dB"],"en|es":["0x5EC045788659159e2E2A725361DF4Dc271edB7dB"],"en|fr":["0x5EC045788659159e2E2A725361DF4Dc271edB7dB"],"en|ja":["0x5EC045788659159e2E2A725361DF4Dc271edB7dB"],"en|ko":["0x5EC045788659159e2E2A725361DF4Dc271edB7dB"],"en|pt":["0x5EC045788659159e2E2A725361DF4Dc271edB7dB"],"en|ru":["0x5EC045788659159e2E2A725361DF4Dc271edB7dB"],"en|tr":["0x5EC045788659159e2E2A725361DF4Dc271edB7dB"],"en|zh":["0x5EC045788659159e2E2A725361DF4Dc271edB7dB"]}}'

[context.production.environment]
  DEFAULT_CHAIN_ID='1'
  FORTMATIC_API_KEY='pk_live_E4C12880C70B02F9'
  AVAILABLE_LANGUAGE_GROUP_PAIRS='["en|fr","en|es","en|pt","de|en","en|ru","en|tr","en|zh"]'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/*/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/*/*/*"
  to = "/index.html"
  status = 200
  force = false
